### ISSUE TITLE
Im having problems getting this lib working with multi-dex enabled.

### ISSUE THREAD

**Issue by sirvon** [Vungle/publisher-sample-android#4]
Here's the error:

```java

01-25 04:46:01.986  27213-27282/com.loqooapps.default E/VungleAsync﹕ java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationClient;
            at com.vungle.publisher.location.GooglePlayServicesDetailedLocationProvider.c(vungle:71)
            at com.vungle.publisher.location.GooglePlayServicesDetailedLocationProvider.a(vungle:34)
            at com.vungle.publisher.location.AndroidLocation.b(vungle:35)
            at com.vungle.publisher.protocol.message.RequestAd$Demographic$Location$Factory.b(vungle:176)
            at com.vungle.publisher.protocol.message.RequestAd$Demographic$Factory.b(vungle:126)
            at com.vungle.publisher.protocol.message.RequestAd$a.b(vungle:80)
            at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:71)
            at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:68)
            at com.vungle.publisher.inject.ConfigurablePublisherModule.a(vungle:325)
            at com.vungle.publisher.inject.ConfigurablePublisherModule$$ModuleAdapter$ProvideRequestLocalAdHttpTransactionProvidesAdapter.get(vungle:849)
            at com.vungle.publisher.inject.ConfigurablePublisherModule$$ModuleAdapter$ProvideRequestLocalAdHttpTransactionProvidesAdapter.get(vungle:810)
            at com.vungle.publisher.protocol.ProtocolHttpGateway$2.run(vungle:127)
            at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:233)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationClient" on path: DexPathList[[zip file "/data/app/com.loqooapps.default-1/base.apk"],nativeLibraryDirectories=[/data/app/com.loqooapps.default-1/lib/arm, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.vungle.publisher.location.GooglePlayServicesDetailedLocationProvider.c(vungle:71)
            at com.vungle.publisher.location.GooglePlayServicesDetailedLocationProvider.a(vungle:34)
            at com.vungle.publisher.location.AndroidLocation.b(vungle:35)
            at com.vungle.publisher.protocol.message.RequestAd$Demographic$Location$Factory.b(vungle:176)
            at com.vungle.publisher.protocol.message.RequestAd$Demographic$Factory.b(vungle:126)
            at com.vungle.publisher.protocol.message.RequestAd$a.b(vungle:80)
            at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:71)
            at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:68)
            at com.vungle.publisher.inject.ConfigurablePublisherModule.a(vungle:325)
            at com.vungle.publisher.inject.ConfigurablePublisherModule$$ModuleAdapter$ProvideRequestLocalAdHttpTransactionProvidesAdapter.get(vungle:849)
            at com.vungle.publisher.inject.ConfigurablePublisherModule$$ModuleAdapter$ProvideRequestLocalAdHttpTransactionProvidesAdapter.get(vungle:810)
            at com.vungle.publisher.protocol.ProtocolHttpGateway$2.run(vungle:127)
            at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:233)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
    Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.location.LocationClient
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 17 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
01-25 04:46:02.281  27213-27322/com.loqooapps.default W/ResourcesManager﹕ Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
01-25 04:46:02.299  27213-27282/com.loqooapps.default E/AndroidRuntime﹕ FATAL EXCEPTION: VungleAsyncMainThread-1
    Process: com.loqooapps.default, PID: 27213
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationClient;
            at com.vungle.publisher.location.GooglePlayServicesDetailedLocationProvider.c(vungle:71)
            at com.vungle.publisher.location.GooglePlayServicesDetailedLocationProvider.a(vungle:34)
            at com.vungle.publisher.location.AndroidLocation.b(vungle:35)
            at com.vungle.publisher.protocol.message.RequestAd$Demographic$Location$Factory.b(vungle:176)
            at com.vungle.publisher.protocol.message.RequestAd$Demographic$Factory.b(vungle:126)
            at com.vungle.publisher.protocol.message.RequestAd$a.b(vungle:80)
            at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:71)
            at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:68)
            at com.vungle.publisher.inject.ConfigurablePublisherModule.a(vungle:325)
            at com.vungle.publisher.inject.ConfigurablePublisherModule$$ModuleAdapter$ProvideRequestLocalAdHttpTransactionProvidesAdapter.get(vungle:849)
            at com.vungle.publisher.inject.ConfigurablePublisherModule$$ModuleAdapter$ProvideRequestLocalAdHttpTransactionProvidesAdapter.get(vungle:810)
            at com.vungle.publisher.protocol.ProtocolHttpGateway$2.run(vungle:127)
            at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:233)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationClient" on path: DexPathList[[zip file "/data/app/com.loqooapps.default-1/base.apk"],nativeLibraryDirectories=[/data/app/com.loqooapps.default-1/lib/arm, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.vungle.publisher.location.GooglePlayServicesDetailedLocationProvider.c(vungle:71)
            at com.vungle.publisher.location.GooglePlayServicesDetailedLocationProvider.a(vungle:34)
            at com.vungle.publisher.location.AndroidLocation.b(vungle:35)
            at com.vungle.publisher.protocol.message.RequestAd$Demographic$Location$Factory.b(vungle:176)
            at com.vungle.publisher.protocol.message.RequestAd$Demographic$Factory.b(vungle:126)
            at com.vungle.publisher.protocol.message.RequestAd$a.b(vungle:80)
            at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:71)
            at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:68)
            at com.vungle.publisher.inject.ConfigurablePublisherModule.a(vungle:325)
            at com.vungle.publisher.inject.ConfigurablePublisherModule$$ModuleAdapter$ProvideRequestLocalAdHttpTransactionProvidesAdapter.get(vungle:849)
            at com.vungle.publisher.inject.ConfigurablePublisherModule$$ModuleAdapter$ProvideRequestLocalAdHttpTransactionProvidesAdapter.get(vungle:810)
            at com.vungle.publisher.protocol.ProtocolHttpGateway$2.run(vungle:127)
            at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:233)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
    Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.location.LocationClient
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 17 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

```

**Comment by sirvon** [comment]
I do have google play services as a dependencies but not the one in vungle's lib folder install.
I'm using the latest one from the repos.

**Comment by markmooibroek** [comment]
Nothing to do with multi dex. I also have the latest GMS services and there is a breaking change in the latest version of GMS. @vungle any ETA on upgrading to a new version? v4.0 is from ages ago. Currently GMS is at v6.5 =)

**Comment by Maixy** [comment]
@markmooibroek We're currently compatible with Google Play Services up to 6.1, but keep an eye out on the Vungle Dashboard for our next release, which will definitely support the latest Google Play Services version!
